### PR TITLE
removed max-height and overflow scroll from _show.styl

### PR DESCRIPTION
**Pull request by simeydk**
Removed max-height and overflow scroll from _show.styl, which will fix [issue 32](https://github.com/wesbos/Syntax/issues/32)

### CODE REVIEW

**Comment by wesbos** [comment]
Thank you!

**Comment by simeydk** [comment]
It's a pleasure! Thanks for merging my first PR!

Big fan of the show, by the way. "Git for Dummies" / "My first pull request" might be an idea for a topic for a show, or part of a show (not sure if it's assumed knowledge for your deemed target audience)? Do you take suggestions for show topics?

**Comment by wesbos** [comment]
We do - we have a git show planned but one specifically focused on beginners a great idea :D

**Comment by simeydk** [comment]
Cool. Looking forward to the git show. 

_Tangent_: My other suggestion is "Testing for dummies". I've heard a lot about it and it sounds good in principle, but not sure where to start in terms of doing testing from first principles or via a framework. And how does testing work for interfaces? Do you test HTML output / actual pixels / what?

**Pull request merged**
