### PR TITLE
Fix outline colors on subscribe links and volume div

### PR DESCRIPTION
**Pull request by ben-foster**
Subscribe links outline color on focus was set to black, which was invisible against the black background. Updated to theme yellow.

Also, volume div was set to the webkit default blue while its sibling elements were set to the theme yellow. Updated to theme yellow.

P.S. this is my first pull request!

### CODE REVIEW

**Comment by ben-foster** [comment]
Hey Sergiy, I think I fixed the issue -- could you confirm? Thanks!

**Comment by ben-foster** [comment]
@416serg did I fix the issue you noted? I saw you added the await additionalinfo() label, wasn't sure if that meant you were waiting on me or not.

**Comment by 416serg** [comment]
@ben-foster hey Ben, sorry for the confusion. However, I am still not sure as to why the `package-lock.json` file is being committed in the first place 🤔There seem to be some package differences there. Would you be able to just commit the `_player.styl`, `_subscribe.styl` and `style.styl` files so that it's an easy and clean merge without changing anything in `package-lock.json`? 😅 Thanks!

**Comment by 416serg** [comment]
@ben-foster this is what I think happens in the background of git https://giphy.com/gifs/git-merge-cFkiFMDg3iFoI 😂

Looking forward to the new PR, closing this for now!

**Pull request closed without merging**
