### PR TITLE
svg icons added and a11y issues fixed

### PR DESCRIPTION
**Pull request by saigowthamr**
syntax

### CODE REVIEW

**Comment by wesbos** [comment]
Hey! can you re-open this ?I'd love to merge it :)

**Comment by saigowthamr** [comment]
Actually, i deleted the repo once i saw your comment then I mailed to GitHub support  to get back the 
deleted repo so they restored it now.

**Comment by saigowthamr** [comment]
success

**Comment by wesbos** [comment]
thank you so much - very helpful!

**Pull request merged**
