### PR TITLE
Use Link on sponsor anchor

### PR DESCRIPTION
**Pull request by Mindaugas-Jacionis**
[Proposal] I suggest using `Link` on footer sponsorship anchor as well. 🙂

### CODE REVIEW

**Comment by 416serg** [comment]
@Mindaugas-Jacionis should there be an empty anchor between the `Link` component? https://github.com/zeit/next.js/#with-link

**Comment by Mindaugas-Jacionis** [comment]
@416serg - I was unable to find in the docs why they put empty anchor, but in `next.js` source of `Link` component I can see they handle this scenario - here's a [link](https://github.com/zeit/next.js/blob/58583a2b811e4ac4a3b475e239eb6480da5d1dea/packages/next-server/lib/link.js#L118). Basically if `children` of `Link` are of type `string` then it takes care of wrapping it in an anchor. 

Should I still add an empty anchor? 🙂

**Comment by 416serg** [comment]
@Mindaugas-Jacionis Yeah, I think it's best to keep it as docs suggest, even though they work their magic under the hood and make sure it's all good 👍🏼

Once you've added that commit here I'll merge the PR 😃

Thanks again!

**Comment by Mindaugas-Jacionis** [comment]
@416serg - I've added missing anchor 👍 🙂

**Comment by 416serg** [comment]
thanks @Mindaugas-Jacionis 👍🏼

**Pull request merged**
