### PR TITLE
Remove custom server, use SSG, upgrade to Vercel

### PR DESCRIPTION
**Pull request by timneutkens**
Implements Next.js `getStaticProps` making the site be served from the Vercel Edge Network automatically as a static site.

Also adds incremental static regeneration: https://nextjs.org/blog/next-9-4#incremental-static-regeneration-beta as the episodes are added before they go live and are time-based.

Removed the need for API routes as you can do transforms on data directly in getStaticProps :100:

Furthermore you'll be able to connect the GitHub integration and get automatic preview urls through https://vercel.com/new

Deployed under my own account: https://syntax-no1e5j837.now.sh/

### CODE REVIEW

**Comment by timneutkens** [comment]
One thing I noticed is that new markdown files could be added before the episode is published, which obviously might be an issue if this does end up being completely static as the site will need a rebuild when a new item is added.

**Comment by wesbos** [comment]
Hey Tim! Thanks a ton for this.  Really cool!

Having the markdown files with a timestamp in the future is how we release the epsiodes. Could we just hide them on the client? They just need to show up once that timestamp is passed.

**Comment by timneutkens** [comment]
@wesbos in theory you could definitely do that, guess the main problem is that you'd want to show the content on the homepage for it to be indexed, maybe not though 🤔

**Comment by wesbos** [comment]
Hmmmm, yah we often do it 2-4 weeks ahead of time, so that isn't a great option.

**Comment by wesbos** [comment]
Talking to @lfades about this - we can use Revalidation for this - will take a look in a few weeks

**Comment by wesbos** [comment]
@rauchg this is the release feature we are referring to

**Comment by timneutkens** [comment]
@wesbos I'll revisit this when we figure out rolling out after the published-at date 👍

**Comment by timneutkens** [comment]
@wesbos I've updated the PR 👍

**Comment by wesbos** [comment]
@timneutkens I'm getting all 404s when I try run this locally. Anything I need to do?

**Comment by timneutkens** [comment]
Having a look!

**Comment by wesbos** [comment]
thanks! 

seems the url /shows/latest/latest works, but not index, nor any /show/[num]/[slug]

Also I don't see any of the API has been moved, I assume I can do that with API routes?

**Comment by timneutkens** [comment]
@wesbos should be good now, yeah the API can be exposed as such, didn't know it was a public api.

**Comment by wesbos** [comment]
thanks a ton for the quick look! Let me try it now

**Comment by Timer** [comment]
@wesbos re-added the API endpoints!

**Comment by wesbos** [comment]
ah thanks! I added the one I needed but Ill take a look at this.  Not sure how you got the deploy to work so fast, been waiting for almost 30 mins for  mine to deploy

**Comment by wesbos** [comment]
Just going to merge this and get it going :)

**Comment by Timer** [comment]
Let us know if you need help with anything else. I'm having the team look into that 30m deploy, seems to have been a one-off.

**Comment by wesbos** [comment]
Yeah new deploys are fast! Chalk it up to a one off.


On June 24, 2020 at 12:27 PM, Joe Haddad (notifications@github.com) wrote:
Let us know if you need help with anything else. I'm having the team look into that 30m deploy, seems to have been a one-off due to upstream S3 errors.

**Pull request merged**
