### PR TITLE
Remove the outline from the player button

### PR DESCRIPTION
**Pull request by BrahimS**
Hello,
This is a small contribution, I thought the outline on the player button is disturbing the beautiful design.
screen shot 2018-08-21 at 13 54 21

### CODE REVIEW

**Comment by BrahimS** [comment]
@wesbos Yep, that is even butter, i've changed the outline colour to black = #1d1d1d.

**Comment by wesbos** [comment]
Can you show a screenshot? I'm worried black on black won't be accessible either - something like yellow is probably better :) 

Also a re-base on master would be great so we don't have all these commits coming along :D

**Comment by BrahimS** [comment]
The black out line looks like this : 
screen shot 2018-08-21 at 18 08 53
The yellow one like this: 
screen shot 2018-08-21 at 18 10 50

**Comment by BrahimS** [comment]
Hi Wes, in case here is the link for my commit, Please tell me if the $yellow work for you. :)
[commit](https://github.com/wesbos/Syntax/pull/134/commits/aa53b648cc22a9645d7fc65e719bad8009c97e3e)

**Pull request closed without merging**
